import type { GodConstellation, GodConstellationPoint } from "./god-constellations";

type Landmark = readonly [name: string, x: number, y: number, power?: number];

/**
 * Convert named, hand-picked landmarks into the compact indexed data consumed
 * by the SVG renderer. Keeping names here makes individual joints and divine
 * symbols straightforward to tune against the reference portraits.
 */
function createConstellation<const T extends readonly Landmark[]>(
  landmarks: T,
  links: readonly (readonly [T[number][0], T[number][0]])[],
): GodConstellation {
  const indexes = new Map<string, number>(landmarks.map(([name], index) => [name, index]));

  return {
    points: landmarks.map(([, x, y, power]) =>
      power === undefined
        ? ([x, y] as GodConstellationPoint)
        : ([x, y, power] as GodConstellationPoint),
    ),
    lines: links.map(([from, to]) => {
      const fromIndex = indexes.get(from);
      const toIndex = indexes.get(to);
      if (fromIndex === undefined || toIndex === undefined) {
        throw new Error(`Unknown god landmark link: ${from} -> ${to}`);
      }
      return [fromIndex, toIndex] as const;
    }),
  };
}

/**
 * Anatomical and symbolic constellations traced by hand over the fourteen
 * portraits in `UI_test/image_processed/lighter`. Unlike the former contour
 * sampler, these links describe a figure: head, shoulders, articulated limbs,
 * stance, and the deity's identifying object.
 */
export const GOD_LANDMARK_CONSTELLATIONS: Readonly<Record<string, GodConstellation>> = {
  tuvi: createConstellation(
    [
      ["lightningTip", 29, 1, 1.5],
      ["lightningFork", 24, 14, 1.15],
      ["raisedHand", 31, 25, 1.25],
      ["leftShoulder", 40, 32],
      ["head", 50, 19, 1.4],
      ["rightShoulder", 59, 32],
      ["chest", 50, 42, 1.15],
      ["rightElbow", 64, 49],
      ["rightHand", 68, 65, 1.1],
      ["thunderSigil", 81, 43, 1.3],
      ["thunderTail", 77, 54],
      ["hip", 51, 57, 1.1],
      ["leftKnee", 43, 70],
      ["leftFoot", 38, 89, 1.15],
      ["rightKnee", 58, 71],
      ["rightFoot", 64, 90, 1.15],
    ],
    [
      ["lightningTip", "lightningFork"],
      ["lightningFork", "raisedHand"],
      ["raisedHand", "leftShoulder"],
      ["leftShoulder", "head"],
      ["head", "rightShoulder"],
      ["leftShoulder", "chest"],
      ["rightShoulder", "chest"],
      ["rightShoulder", "rightElbow"],
      ["rightElbow", "rightHand"],
      ["rightHand", "thunderTail"],
      ["thunderTail", "thunderSigil"],
      ["chest", "hip"],
      ["hip", "leftKnee"],
      ["leftKnee", "leftFoot"],
      ["hip", "rightKnee"],
      ["rightKnee", "rightFoot"],
    ],
  ),

  thienphu: createConstellation(
    [
      ["scepterCrown", 26, 8, 1.45],
      ["scepterHand", 29, 24, 1.2],
      ["scepterFoot", 34, 61],
      ["leftShoulder", 40, 30],
      ["head", 50, 17, 1.4],
      ["rightShoulder", 59, 30],
      ["chest", 50, 41, 1.15],
      ["rightElbow", 65, 39],
      ["rightHand", 71, 48, 1.1],
      ["peacockHead", 76, 48, 1.25],
      ["peacockBody", 79, 58],
      ["tailEyeTop", 75, 69, 1.1],
      ["tailEyeOuter", 83, 77, 1.1],
      ["tailEyeLower", 79, 87, 1.1],
      ["hip", 50, 56, 1.1],
      ["leftKnee", 43, 70],
      ["leftFoot", 38, 89, 1.15],
      ["rightKnee", 57, 70],
      ["rightFoot", 63, 89, 1.15],
    ],
    [
      ["scepterCrown", "scepterHand"],
      ["scepterHand", "scepterFoot"],
      ["scepterHand", "leftShoulder"],
      ["leftShoulder", "head"],
      ["head", "rightShoulder"],
      ["leftShoulder", "chest"],
      ["rightShoulder", "chest"],
      ["rightShoulder", "rightElbow"],
      ["rightElbow", "rightHand"],
      ["rightHand", "peacockHead"],
      ["peacockHead", "peacockBody"],
      ["peacockBody", "tailEyeTop"],
      ["tailEyeTop", "tailEyeOuter"],
      ["tailEyeOuter", "tailEyeLower"],
      ["chest", "hip"],
      ["hip", "leftKnee"],
      ["leftKnee", "leftFoot"],
      ["hip", "rightKnee"],
      ["rightKnee", "rightFoot"],
    ],
  ),

  thatsat: createConstellation(
    [
      ["spearTip", 13, 2, 1.5],
      ["spearGrip", 29, 20, 1.2],
      ["leftShoulder", 41, 28],
      ["head", 51, 17, 1.4],
      ["rightShoulder", 61, 28],
      ["chest", 51, 39, 1.15],
      ["shieldTop", 69, 32, 1.05],
      ["shieldOuter", 78, 44, 1.15],
      ["shieldBottom", 72, 55, 1.05],
      ["shieldBoss", 70, 44, 1.25],
      ["hip", 51, 54, 1.1],
      ["leftKnee", 43, 68],
      ["leftFoot", 39, 86, 1.15],
      ["rightKnee", 59, 67],
      ["rightFoot", 66, 84, 1.15],
    ],
    [
      ["spearTip", "spearGrip"],
      ["spearGrip", "leftShoulder"],
      ["leftShoulder", "head"],
      ["head", "rightShoulder"],
      ["leftShoulder", "chest"],
      ["rightShoulder", "chest"],
      ["rightShoulder", "shieldTop"],
      ["shieldTop", "shieldOuter"],
      ["shieldOuter", "shieldBottom"],
      ["shieldBottom", "shieldBoss"],
      ["shieldBoss", "shieldTop"],
      ["chest", "hip"],
      ["hip", "leftKnee"],
      ["leftKnee", "leftFoot"],
      ["hip", "rightKnee"],
      ["rightKnee", "rightFoot"],
    ],
  ),

  phaquan: createConstellation(
    [
      ["flameCrown", 20, 2, 1.5],
      ["flameCore", 25, 13, 1.25],
      ["raisedHand", 31, 28, 1.2],
      ["leftShoulder", 40, 31],
      ["head", 50, 20, 1.4],
      ["rightShoulder", 60, 31],
      ["chest", 50, 41, 1.15],
      ["rightElbow", 68, 41],
      ["rightHand", 75, 50, 1.1],
      ["chainLinkTop", 78, 58],
      ["chainLinkMid", 73, 65, 1.05],
      ["chainLinkEnd", 82, 71, 1.15],
      ["hip", 51, 56, 1.1],
      ["leftKnee", 43, 69],
      ["leftFoot", 36, 82, 1.15],
      ["rightKnee", 59, 70],
      ["rightFoot", 65, 88, 1.15],
    ],
    [
      ["flameCrown", "flameCore"],
      ["flameCore", "raisedHand"],
      ["raisedHand", "leftShoulder"],
      ["leftShoulder", "head"],
      ["head", "rightShoulder"],
      ["leftShoulder", "chest"],
      ["rightShoulder", "chest"],
      ["rightShoulder", "rightElbow"],
      ["rightElbow", "rightHand"],
      ["rightHand", "chainLinkTop"],
      ["chainLinkTop", "chainLinkMid"],
      ["chainLinkMid", "chainLinkEnd"],
      ["chest", "hip"],
      ["hip", "leftKnee"],
      ["leftKnee", "leftFoot"],
      ["hip", "rightKnee"],
      ["rightKnee", "rightFoot"],
    ],
  ),

  thamlang: createConstellation(
    [
      ["mirrorCrown", 29, 7, 1.45],
      ["raisedHand", 30, 23, 1.2],
      ["leftShoulder", 41, 29],
      ["head", 50, 17, 1.4],
      ["rightShoulder", 59, 29],
      ["chest", 50, 41, 1.15],
      ["leftElbow", 34, 40],
      ["leftHand", 33, 51, 1.05],
      ["rightElbow", 64, 41],
      ["rightHand", 70, 50, 1.05],
      ["doveWing", 18, 47, 1.2],
      ["shellCrown", 21, 73, 1.25],
      ["hip", 50, 55, 1.1],
      ["leftKnee", 42, 68],
      ["leftFoot", 34, 89, 1.15],
      ["rightKnee", 57, 70],
      ["rightFoot", 64, 90, 1.15],
    ],
    [
      ["mirrorCrown", "raisedHand"],
      ["raisedHand", "leftShoulder"],
      ["leftShoulder", "head"],
      ["head", "rightShoulder"],
      ["leftShoulder", "chest"],
      ["rightShoulder", "chest"],
      ["leftShoulder", "leftElbow"],
      ["leftElbow", "leftHand"],
      ["leftHand", "doveWing"],
      ["leftHand", "shellCrown"],
      ["rightShoulder", "rightElbow"],
      ["rightElbow", "rightHand"],
      ["chest", "hip"],
      ["hip", "leftKnee"],
      ["leftKnee", "leftFoot"],
      ["hip", "rightKnee"],
      ["rightKnee", "rightFoot"],
    ],
  ),

  thaiduong: createConstellation(
    [
      ["sunCrown", 50, 3, 1.5],
      ["sunLeft", 39, 10, 1.05],
      ["sunRight", 60, 10, 1.05],
      ["head", 50, 17, 1.4],
      ["raisedFlame", 22, 8, 1.3],
      ["raisedHand", 25, 23, 1.15],
      ["leftShoulder", 40, 29],
      ["rightShoulder", 60, 30],
      ["chest", 50, 40, 1.15],
      ["rightElbow", 68, 42],
      ["rightHand", 75, 49, 1.1],
      ["hip", 50, 55, 1.1],
      ["leftKnee", 42, 68],
      ["leftFoot", 36, 85, 1.15],
      ["rightKnee", 57, 67],
      ["rightFoot", 65, 86, 1.15],
    ],
    [
      ["sunCrown", "sunLeft"],
      ["sunCrown", "sunRight"],
      ["sunLeft", "head"],
      ["sunRight", "head"],
      ["raisedFlame", "raisedHand"],
      ["raisedHand", "leftShoulder"],
      ["leftShoulder", "head"],
      ["head", "rightShoulder"],
      ["leftShoulder", "chest"],
      ["rightShoulder", "chest"],
      ["rightShoulder", "rightElbow"],
      ["rightElbow", "rightHand"],
      ["chest", "hip"],
      ["hip", "leftKnee"],
      ["leftKnee", "leftFoot"],
      ["hip", "rightKnee"],
      ["rightKnee", "rightFoot"],
    ],
  ),

  thaiam: createConstellation(
    [
      ["moonCrown", 32, 8, 1.3],
      ["moonCenter", 21, 29, 1.2],
      ["moonFoot", 31, 50, 1.15],
      ["head", 49, 17, 1.4],
      ["rearHand", 26, 28, 1.1],
      ["leftShoulder", 41, 29],
      ["rightShoulder", 56, 30],
      ["chest", 49, 40, 1.15],
      ["frontElbow", 68, 29],
      ["bowHand", 78, 28, 1.2],
      ["bowCrown", 64, 2, 1.25],
      ["bowFoot", 69, 55, 1.2],
      ["arrowTip", 91, 28, 1.4],
      ["hip", 51, 55, 1.1],
      ["leftKnee", 45, 69],
      ["leftFoot", 43, 87, 1.15],
      ["rightKnee", 58, 69],
      ["rightFoot", 65, 87, 1.15],
    ],
    [
      ["moonCrown", "moonCenter"],
      ["moonCenter", "moonFoot"],
      ["moonCenter", "rearHand"],
      ["rearHand", "leftShoulder"],
      ["leftShoulder", "head"],
      ["head", "rightShoulder"],
      ["leftShoulder", "chest"],
      ["rightShoulder", "chest"],
      ["rightShoulder", "frontElbow"],
      ["frontElbow", "bowHand"],
      ["bowCrown", "bowHand"],
      ["bowHand", "bowFoot"],
      ["rearHand", "bowHand"],
      ["bowHand", "arrowTip"],
      ["chest", "hip"],
      ["hip", "leftKnee"],
      ["leftKnee", "leftFoot"],
      ["hip", "rightKnee"],
      ["rightKnee", "rightFoot"],
    ],
  ),

  vukhuc: createConstellation(
    [
      ["caduceusLeftWing", 15, 8, 1.2],
      ["caduceusCrown", 24, 5, 1.4],
      ["caduceusRightWing", 31, 3, 1.2],
      ["caduceusCoil", 23, 15, 1.1],
      ["staffHand", 27, 28, 1.2],
      ["leftShoulder", 39, 30],
      ["head", 50, 18, 1.4],
      ["rightShoulder", 59, 29],
      ["chest", 50, 39, 1.15],
      ["rightElbow", 68, 39],
      ["bagHand", 78, 47, 1.1],
      ["coinBag", 76, 56, 1.25],
      ["hip", 49, 49, 1.1],
      ["leftKnee", 31, 53],
      ["leftAnkle", 42, 69],
      ["leftFoot", 40, 77, 1.15],
      ["rightKnee", 61, 59],
      ["rightAnkle", 70, 78],
      ["rightFoot", 68, 89, 1.2],
      ["ankleWing", 75, 77, 1.2],
    ],
    [
      ["caduceusLeftWing", "caduceusCrown"],
      ["caduceusCrown", "caduceusRightWing"],
      ["caduceusCrown", "caduceusCoil"],
      ["caduceusCoil", "staffHand"],
      ["staffHand", "leftShoulder"],
      ["leftShoulder", "head"],
      ["head", "rightShoulder"],
      ["leftShoulder", "chest"],
      ["rightShoulder", "chest"],
      ["rightShoulder", "rightElbow"],
      ["rightElbow", "bagHand"],
      ["bagHand", "coinBag"],
      ["chest", "hip"],
      ["hip", "leftKnee"],
      ["leftKnee", "leftAnkle"],
      ["leftAnkle", "leftFoot"],
      ["hip", "rightKnee"],
      ["rightKnee", "rightAnkle"],
      ["rightAnkle", "rightFoot"],
      ["rightAnkle", "ankleWing"],
    ],
  ),

  liemtrinh: createConstellation(
    [
      ["balanceCrown", 26, 3, 1.35],
      ["balanceGrip", 31, 20, 1.2],
      ["balanceBeamLeft", 21, 21],
      ["leftPan", 17, 36, 1.2],
      ["balanceBeamRight", 38, 25],
      ["rightPan", 35, 36, 1.2],
      ["leftShoulder", 41, 28],
      ["head", 50, 17, 1.4],
      ["rightShoulder", 60, 30],
      ["chest", 51, 41, 1.15],
      ["rightElbow", 66, 43],
      ["swordHand", 70, 53, 1.1],
      ["swordTip", 78, 86, 1.3],
      ["hip", 52, 55, 1.1],
      ["leftKnee", 44, 69],
      ["leftFoot", 40, 89, 1.15],
      ["rightKnee", 59, 70],
      ["rightFoot", 65, 89, 1.15],
    ],
    [
      ["balanceCrown", "balanceGrip"],
      ["balanceGrip", "balanceBeamLeft"],
      ["balanceBeamLeft", "leftPan"],
      ["balanceGrip", "balanceBeamRight"],
      ["balanceBeamRight", "rightPan"],
      ["balanceGrip", "leftShoulder"],
      ["leftShoulder", "head"],
      ["head", "rightShoulder"],
      ["leftShoulder", "chest"],
      ["rightShoulder", "chest"],
      ["rightShoulder", "rightElbow"],
      ["rightElbow", "swordHand"],
      ["swordHand", "swordTip"],
      ["chest", "hip"],
      ["hip", "leftKnee"],
      ["leftKnee", "leftFoot"],
      ["hip", "rightKnee"],
      ["rightKnee", "rightFoot"],
    ],
  ),

  thienco: createConstellation(
    [
      ["spearTip", 22, 2, 1.45],
      ["spearHand", 31, 29, 1.2],
      ["spearFoot", 41, 81],
      ["leftShoulder", 41, 30],
      ["head", 51, 17, 1.4],
      ["rightShoulder", 60, 31],
      ["chest", 51, 43, 1.15],
      ["shieldTop", 69, 35, 1.05],
      ["shieldOuter", 78, 49, 1.15],
      ["shieldBottom", 72, 62, 1.05],
      ["shieldBoss", 70, 49, 1.25],
      ["hip", 52, 56, 1.1],
      ["leftKnee", 44, 70],
      ["leftFoot", 40, 88, 1.15],
      ["rightKnee", 57, 70],
      ["rightFoot", 61, 88, 1.15],
      ["owlHead", 28, 65, 1.25],
      ["owlBody", 27, 75],
      ["owlFeet", 28, 84, 1.1],
    ],
    [
      ["spearTip", "spearHand"],
      ["spearHand", "spearFoot"],
      ["spearHand", "leftShoulder"],
      ["leftShoulder", "head"],
      ["head", "rightShoulder"],
      ["leftShoulder", "chest"],
      ["rightShoulder", "chest"],
      ["rightShoulder", "shieldTop"],
      ["shieldTop", "shieldOuter"],
      ["shieldOuter", "shieldBottom"],
      ["shieldBottom", "shieldBoss"],
      ["shieldBoss", "shieldTop"],
      ["chest", "hip"],
      ["hip", "leftKnee"],
      ["leftKnee", "leftFoot"],
      ["hip", "rightKnee"],
      ["rightKnee", "rightFoot"],
      ["spearFoot", "owlHead"],
      ["owlHead", "owlBody"],
      ["owlBody", "owlFeet"],
    ],
  ),

  thienluong: createConstellation(
    [
      ["wheatLeft", 18, 6, 1.2],
      ["wheatCrown", 23, 3, 1.4],
      ["wheatRight", 29, 7, 1.2],
      ["wheatHand", 27, 25, 1.2],
      ["leftShoulder", 38, 29],
      ["head", 49, 16, 1.4],
      ["rightShoulder", 59, 29],
      ["chest", 49, 40, 1.15],
      ["rightElbow", 65, 42],
      ["basketHand", 67, 55, 1.05],
      ["harvestBasket", 65, 65, 1.25],
      ["hip", 49, 56, 1.1],
      ["leftKnee", 41, 70],
      ["leftFoot", 37, 87, 1.15],
      ["rightKnee", 56, 70],
      ["rightFoot", 61, 88, 1.15],
    ],
    [
      ["wheatLeft", "wheatHand"],
      ["wheatCrown", "wheatHand"],
      ["wheatRight", "wheatHand"],
      ["wheatHand", "leftShoulder"],
      ["leftShoulder", "head"],
      ["head", "rightShoulder"],
      ["leftShoulder", "chest"],
      ["rightShoulder", "chest"],
      ["rightShoulder", "rightElbow"],
      ["rightElbow", "basketHand"],
      ["basketHand", "harvestBasket"],
      ["chest", "hip"],
      ["hip", "leftKnee"],
      ["leftKnee", "leftFoot"],
      ["hip", "rightKnee"],
      ["rightKnee", "rightFoot"],
    ],
  ),

  thientuong: createConstellation(
    [
      ["staffCrown", 23, 4, 1.45],
      ["staffHand", 24, 31, 1.2],
      ["staffFoot", 27, 88, 1.1],
      ["leftShoulder", 39, 29],
      ["head", 50, 16, 1.4],
      ["rightShoulder", 59, 30],
      ["chest", 50, 41, 1.15],
      ["rightHand", 63, 48, 1.05],
      ["hip", 50, 56, 1.1],
      ["leftKnee", 44, 70],
      ["leftFoot", 40, 87, 1.15],
      ["rightKnee", 56, 70],
      ["rightFoot", 60, 87, 1.15],
      ["cerberusLeftHead", 68, 55, 1.2],
      ["cerberusCenterHead", 76, 53, 1.3],
      ["cerberusRightHead", 83, 56, 1.2],
      ["cerberusLeftPaw", 70, 87, 1.1],
      ["cerberusRightPaw", 81, 88, 1.1],
    ],
    [
      ["staffCrown", "staffHand"],
      ["staffHand", "staffFoot"],
      ["staffHand", "leftShoulder"],
      ["leftShoulder", "head"],
      ["head", "rightShoulder"],
      ["leftShoulder", "chest"],
      ["rightShoulder", "chest"],
      ["rightShoulder", "rightHand"],
      ["chest", "hip"],
      ["hip", "leftKnee"],
      ["leftKnee", "leftFoot"],
      ["hip", "rightKnee"],
      ["rightKnee", "rightFoot"],
      ["rightHand", "cerberusLeftHead"],
      ["cerberusLeftHead", "cerberusCenterHead"],
      ["cerberusCenterHead", "cerberusRightHead"],
      ["cerberusLeftHead", "cerberusLeftPaw"],
      ["cerberusRightHead", "cerberusRightPaw"],
    ],
  ),

  thiendong: createConstellation(
    [
      ["gobletCrown", 23, 4, 1.4],
      ["gobletStem", 23, 14, 1.1],
      ["raisedHand", 25, 25, 1.2],
      ["leftShoulder", 38, 31],
      ["head", 49, 19, 1.4],
      ["rightShoulder", 59, 31],
      ["chest", 49, 41, 1.15],
      ["rightElbow", 66, 38],
      ["grapeHand", 69, 44, 1.1],
      ["grapeCrown", 74, 39, 1.15],
      ["grapeCenter", 77, 45, 1.3],
      ["grapeFoot", 73, 50, 1.1],
      ["hip", 49, 56, 1.1],
      ["leftKnee", 42, 68],
      ["leftFoot", 36, 85, 1.15],
      ["rightKnee", 55, 68],
      ["rightFoot", 62, 85, 1.15],
    ],
    [
      ["gobletCrown", "gobletStem"],
      ["gobletStem", "raisedHand"],
      ["raisedHand", "leftShoulder"],
      ["leftShoulder", "head"],
      ["head", "rightShoulder"],
      ["leftShoulder", "chest"],
      ["rightShoulder", "chest"],
      ["rightShoulder", "rightElbow"],
      ["rightElbow", "grapeHand"],
      ["grapeHand", "grapeCrown"],
      ["grapeHand", "grapeCenter"],
      ["grapeHand", "grapeFoot"],
      ["chest", "hip"],
      ["hip", "leftKnee"],
      ["leftKnee", "leftFoot"],
      ["hip", "rightKnee"],
      ["rightKnee", "rightFoot"],
    ],
  ),

  cumon: createConstellation(
    [
      ["torchFlame", 30, 5, 1.45],
      ["raisedHand", 33, 20, 1.2],
      ["leftShoulder", 40, 29],
      ["head", 50, 17, 1.4],
      ["rightShoulder", 59, 29],
      ["chest", 50, 40, 1.15],
      ["leftWingCrown", 29, 37, 1.05],
      ["leftWingTip", 24, 53, 1.15],
      ["rightElbow", 68, 38],
      ["rightHand", 73, 45, 1.1],
      ["irisBloom", 85, 50, 1.3],
      ["hip", 50, 56, 1.1],
      ["leftKnee", 43, 69],
      ["leftFoot", 39, 88, 1.15],
      ["rightKnee", 58, 69],
      ["rightFoot", 63, 90, 1.15],
    ],
    [
      ["torchFlame", "raisedHand"],
      ["raisedHand", "leftShoulder"],
      ["leftShoulder", "head"],
      ["head", "rightShoulder"],
      ["leftShoulder", "chest"],
      ["rightShoulder", "chest"],
      ["leftShoulder", "leftWingCrown"],
      ["leftWingCrown", "leftWingTip"],
      ["rightShoulder", "rightElbow"],
      ["rightElbow", "rightHand"],
      ["rightHand", "irisBloom"],
      ["chest", "hip"],
      ["hip", "leftKnee"],
      ["leftKnee", "leftFoot"],
      ["hip", "rightKnee"],
      ["rightKnee", "rightFoot"],
    ],
  ),
};
